name: Flutter CD
on:
  push:
  pull_request:
    branches:
      - master
    tags:
      - '**'

jobs:
  flutter_cd:
    name: Generate Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo '${{ secrets.FLUTTER_ENV_FILE }}' > .env
      - name: Create key.properties file
        run: |
          echo '${{ secrets.FLUTTER_KEY_PROPERTIES_FILE }}' > /android/key.properties
      - name: Create local.properties file
        run: |
          echo '${{ secrets.FLUTTER_LOCAL_PROPERTIES_FILE }}' > /android/local.properties
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Start Android Release Build
        run: flutter build appbundle
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
            name: android-release
            path: build/app/outputs/bundle/release/app-release.aab